/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.aikar.co/content/groups/aikar/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.dachstein.cloud/nexus/content/repositories/btegermany")
    }

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/releases/")
    }

    maven {
        url = uri("https://repo.fancyplugins.de/releases")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.co.aikar.acf.paper)
    api(libs.dev.triumphteam.triumph.gui.paper) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-platform-bukkit"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-text-serializer-gson"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-platform-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-text-serializer-bungeecord"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-text-serializer-gson-legacy-impl"))
    }
    api(libs.co.aikar.idb.core)
    api(libs.co.aikar.idb.bukkit)
    api(libs.com.zaxxer.hikaricp) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.slf4j", "module" to "slf4j-api"))
    }
    api(libs.fr.mrmicky.fastboard)
    api(libs.net.wesjd.anvilgui)
    api(libs.org.json.json)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.com.github.plan.player.analytics.plan)
    compileOnly(libs.dev.nachwahl.cosmetics)
    compileOnly(libs.com.github.decentsoftware.eu.decentholograms)
    compileOnly(libs.de.oliver.fancyholograms)
    compileOnly(libs.me.clip.placeholderapi) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "net.kyori", "module" to "adventure-platform-bukkit"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.bstats", "module" to "bstats-bukkit"))
    }
    compileOnly(libs.net.luckperms.api)
}

group = "dev.nachwahl"
version = "1.0.2-SNAPSHOT"
description = "Lobby"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
