name: Lobby
version: '${project.version}'
main: dev.nachwahl.lobby.Lobby
api-version: '1.21'
authors: [ Nachwahl,Nudlsupp ]
website: https://bte-germany.de
softdepend:
  - DecentHolograms
  - Plan
depend:
  - FancyHolograms
  - BTEG-Cosmetics
