# https://docs.gradle.org/current/userguide/version_catalogs.html#sec::toml-dependencies-format
[versions]
co-aikar-acf-paper = "0.5.1-SNAPSHOT"
co-aikar-idb-bukkit = "1.0.0-SNAPSHOT"
co-aikar-idb-core = "1.0.0-SNAPSHOT"
com-github-decentsoftware-eu-decentholograms = "2.10.1"
com-github-plan-player-analytics-plan = "5.8.3579"
com-zaxxer-hikaricp = "7.1.0"
de-oliver-fancyholograms = "2.10.0"
dev-nachwahl-cosmetics = "1.0.2"
dev-triumphteam-triumph-gui-paper = "3.1.13"
fr-mrmicky-fastboard = "2.2.0"
io-papermc-paper-paper-api = "1.21.10-R0.1-SNAPSHOT"
me-clip-placeholderapi = "2.12.3"
net-luckperms-api = "5.5"
net-wesjd-anvilgui = "1.10.13-SNAPSHOT"
org-json-json = "20260719"
sonarqube = "7.3.1.8318"
#
# Plugins
#
# https://plugins.gradle.org/plugin/io.freefair.lombok
lombok-plugin = "9.5.0"
# https://github.com/GradleUp/shadow/releases
shadow = "9.6.1"

[libraries]
co-aikar-acf-paper = { module = "co.aikar:acf-paper", version.ref = "co-aikar-acf-paper" }
co-aikar-idb-bukkit = { module = "co.aikar:idb-bukkit", version.ref = "co-aikar-idb-bukkit" }
co-aikar-idb-core = { module = "co.aikar:idb-core", version.ref = "co-aikar-idb-core" }
com-github-decentsoftware-eu-decentholograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "com-github-decentsoftware-eu-decentholograms" }
com-github-plan-player-analytics-plan = { module = "com.github.plan-player-analytics:Plan", version.ref = "com-github-plan-player-analytics-plan" }
com-zaxxer-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "com-zaxxer-hikaricp" }
de-oliver-fancyholograms = { module = "de.oliver:FancyHolograms", version.ref = "de-oliver-fancyholograms" }
dev-nachwahl-cosmetics = { module = "dev.nachwahl:cosmetics", version.ref = "dev-nachwahl-cosmetics" }
dev-triumphteam-triumph-gui-paper = { module = "dev.triumphteam:triumph-gui-paper", version.ref = "dev-triumphteam-triumph-gui-paper" }
fr-mrmicky-fastboard = { module = "fr.mrmicky:fastboard", version.ref = "fr-mrmicky-fastboard" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-paper-api" }
me-clip-placeholderapi = { module = "me.clip:placeholderapi", version.ref = "me-clip-placeholderapi" }
net-luckperms-api = { module = "net.luckperms:api", version.ref = "net-luckperms-api" }
net-wesjd-anvilgui = { module = "net.wesjd:anvilgui", version.ref = "net-wesjd-anvilgui" }
org-json-json = { module = "org.json:json", version.ref = "org-json-json" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
